import type { Alerta, ReporteCiudadano, Convergencia, Metricas } from "@/types";

export const REGIONES_PERU = [
  { id: "ancash", nombre: "Áncash", lat: -9.5277, lon: -77.5278 },
  { id: "cusco", nombre: "Cusco", lat: -13.5319, lon: -71.9675 },
  { id: "lima", nombre: "Lima", lat: -12.0464, lon: -77.0428 },
  { id: "arequipa", nombre: "Arequipa", lat: -16.409, lon: -71.5375 },
  { id: "piura", nombre: "Piura", lat: -5.1945, lon: -80.6328 },
  { id: "loreto", nombre: "Loreto", lat: -3.7437, lon: -73.2516 },
  { id: "puno", nombre: "Puno", lat: -15.8402, lon: -70.0219 },
  { id: "junin", nombre: "Junín", lat: -12.0651, lon: -75.2049 },
];

export const ALERTAS_MOCK: Alerta[] = [
  {
    id: "ALT-2026-0001",
    codigoconvocatoria: "1245678-2026",
    entidad: "Municipalidad Distrital de Independencia",
    rucEntidad: "20131369981",
    proveedor: "CONSTRUCTORA ANDINA EXPRESS SAC",
    rucProveedor: "20612478819",
    edadRucDias: 47,
    unicoPostor: true,
    montoSoles: 2840000,
    fechaBuenaPro: "2026-03-14",
    objeto: "Mejoramiento del servicio educativo I.E. N° 86015 - Huaraz",
    region: "Áncash",
    provincia: "Huaraz",
    distrito: "Independencia",
    lat: -9.5118,
    lon: -77.5301,
    score: 86,
    banderas: [
      {
        regla: "edad_ruc_baja",
        norma: "Heurística — modelo Funes",
        severidad: "alta",
        evidencia: "RUC creado hace 47 días, ganó contrato por S/. 2.84M",
        fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/",
        opinionOece: null,
      },
      {
        regla: "unico_postor_alto",
        norma: "Art. 27 Reglamento Ley 32069",
        severidad: "alta",
        evidencia: "Único postor con oferta al 99.2% del valor referencial",
        fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/",
        opinionOece: "D008-2025",
      },
    ],
    fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/contracts/1245678-2026",
  },
  {
    id: "ALT-2026-0002",
    codigoconvocatoria: "1267901-2026",
    entidad: "Gobierno Regional de Cusco",
    rucEntidad: "20527268878",
    proveedor: "INVERSIONES MARCAVALLE EIRL",
    rucProveedor: "20611239402",
    edadRucDias: 412,
    unicoPostor: false,
    montoSoles: 5120000,
    fechaBuenaPro: "2026-02-08",
    objeto: "Rehabilitación de carretera Cusco - Pisac, tramo II",
    region: "Cusco",
    provincia: "Calca",
    distrito: "Pisac",
    lat: -13.4147,
    lon: -71.8492,
    score: 64,
    banderas: [
      {
        regla: "adenda_25",
        norma: "Art. 34 TUO Ley 30225",
        severidad: "alta",
        evidencia: "Adenda añadió S/. 1.6M sobre monto original S/. 5.1M (31%)",
        fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/",
        opinionOece: "D037-2024",
      },
    ],
    fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/contracts/1267901-2026",
  },
  {
    id: "ALT-2026-0003",
    codigoconvocatoria: "1289012-2026",
    entidad: "Municipalidad Provincial de Carhuaz",
    rucEntidad: "20171298320",
    proveedor: "SERVICIOS GENERALES TINCO SAC",
    rucProveedor: "20612998001",
    edadRucDias: 22,
    unicoPostor: true,
    montoSoles: 980000,
    fechaBuenaPro: "2026-04-02",
    objeto: "Adquisición de materiales para obras de saneamiento",
    region: "Áncash",
    provincia: "Carhuaz",
    distrito: "Carhuaz",
    lat: -9.276,
    lon: -77.6437,
    score: 78,
    banderas: [
      {
        regla: "edad_ruc_baja",
        norma: "Heurística — modelo Funes",
        severidad: "alta",
        evidencia: "RUC creado hace 22 días, ganó contrato por S/. 980K",
        fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/",
        opinionOece: null,
      },
      {
        regla: "unico_postor_alto",
        norma: "Art. 27 Reglamento Ley 32069",
        severidad: "media",
        evidencia: "Único postor con oferta al 97.8% del valor referencial",
        fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/",
        opinionOece: "D008-2025",
      },
    ],
    fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/contracts/1289012-2026",
  },
  {
    id: "ALT-2026-0004",
    codigoconvocatoria: "1301455-2026",
    entidad: "Municipalidad Distrital de San Sebastián",
    rucEntidad: "20174521329",
    proveedor: "INGENIERÍA ANDINA DEL SUR SRL",
    rucProveedor: "20602874119",
    edadRucDias: 1820,
    unicoPostor: false,
    montoSoles: 1750000,
    fechaBuenaPro: "2026-03-25",
    objeto: "Construcción de losa deportiva multifuncional",
    region: "Cusco",
    provincia: "Cusco",
    distrito: "San Sebastián",
    lat: -13.531,
    lon: -71.9075,
    score: 52,
    banderas: [
      {
        regla: "miembro_comite_sin_sican",
        norma: "Art. 8 Reglamento Ley 32069",
        severidad: "media",
        evidencia: "2 de 3 miembros del comité sin certificación SICAN vigente",
        fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/",
        opinionOece: null,
      },
    ],
    fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/contracts/1301455-2026",
  },
  {
    id: "ALT-2026-0005",
    codigoconvocatoria: "1322034-2026",
    entidad: "Municipalidad Distrital de Yungay",
    rucEntidad: "20165498220",
    proveedor: "CORPORACIÓN VIAL RÁNRAHIRCA SAC",
    rucProveedor: "20613789012",
    edadRucDias: 65,
    unicoPostor: true,
    montoSoles: 4250000,
    fechaBuenaPro: "2026-01-19",
    objeto: "Mejoramiento de la transitabilidad vehicular Av. Yungay norte",
    region: "Áncash",
    provincia: "Yungay",
    distrito: "Yungay",
    lat: -9.1378,
    lon: -77.7458,
    score: 91,
    banderas: [
      {
        regla: "edad_ruc_baja",
        norma: "Heurística — modelo Funes",
        severidad: "alta",
        evidencia: "RUC creado hace 65 días, ganó contrato por S/. 4.25M",
        fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/",
        opinionOece: null,
      },
      {
        regla: "unico_postor_alto",
        norma: "Art. 27 Reglamento Ley 32069",
        severidad: "alta",
        evidencia: "Único postor con oferta al 99.8% del valor referencial",
        fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/",
        opinionOece: "D008-2025",
      },
      {
        regla: "socio_sancionado",
        norma: "Art. 50 TUO Ley 30225",
        severidad: "alta",
        evidencia: "Socio mayoritario figura como inhabilitado en otro RUC sancionado",
        fuenteUrl: "https://apps.osce.gob.pe/perfilprov-ui/inhabilitado.xhtml",
        opinionOece: "D012-2024",
      },
    ],
    fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/contracts/1322034-2026",
  },
  {
    id: "ALT-2026-0006",
    codigoconvocatoria: "1340900-2026",
    entidad: "Municipalidad Provincial de Lima",
    rucEntidad: "20131380894",
    proveedor: "CONSORCIO VÍA EXPRESA NORTE",
    rucProveedor: "20614921770",
    edadRucDias: 178,
    unicoPostor: false,
    montoSoles: 18900000,
    fechaBuenaPro: "2026-02-26",
    objeto: "Mantenimiento periódico de la Vía Expresa - tramo norte",
    region: "Lima",
    provincia: "Lima",
    distrito: "Lima",
    lat: -12.0608,
    lon: -77.0345,
    score: 58,
    banderas: [
      {
        regla: "fraccionamiento",
        norma: "Art. 20 Reglamento Ley 32069",
        severidad: "media",
        evidencia: "5 órdenes al mismo contratista por mismo objeto en 23 días, suma > umbral",
        fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/",
        opinionOece: "D024-2023",
      },
    ],
    fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/contracts/1340900-2026",
  },
  {
    id: "ALT-2026-0007",
    codigoconvocatoria: "1351200-2026",
    entidad: "Gobierno Regional de Piura",
    rucEntidad: "20484020611",
    proveedor: "CONSTRUCTORA DEL PACÍFICO NORTE SAC",
    rucProveedor: "20602345678",
    edadRucDias: 34,
    unicoPostor: true,
    montoSoles: 6700000,
    fechaBuenaPro: "2026-03-30",
    objeto: "Construcción del centro de salud Piura - Castilla",
    region: "Piura",
    provincia: "Piura",
    distrito: "Castilla",
    lat: -5.1936,
    lon: -80.6203,
    score: 88,
    banderas: [
      {
        regla: "edad_ruc_baja",
        norma: "Heurística — modelo Funes",
        severidad: "alta",
        evidencia: "RUC creado hace 34 días, ganó contrato por S/. 6.7M",
        fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/",
        opinionOece: null,
      },
      {
        regla: "aportante_es_ganador",
        norma: "Ley 30689 - financiamiento de partidos políticos",
        severidad: "alta",
        evidencia: "Socio aportó S/. 35K al partido del gobernador regional en 2022",
        fuenteUrl: "https://claridadportal.onpe.gob.pe/",
        opinionOece: null,
      },
    ],
    fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/contracts/1351200-2026",
  },
  {
    id: "ALT-2026-0008",
    codigoconvocatoria: "1370012-2026",
    entidad: "Municipalidad Distrital de Recuay",
    rucEntidad: "20171587029",
    proveedor: "TRANSPORTES Y SERVICIOS HUARAZ SAC",
    rucProveedor: "20603127480",
    edadRucDias: 290,
    unicoPostor: true,
    montoSoles: 540000,
    fechaBuenaPro: "2026-04-11",
    objeto: "Servicio de alquiler de maquinaria pesada",
    region: "Áncash",
    provincia: "Recuay",
    distrito: "Recuay",
    lat: -9.7218,
    lon: -77.4533,
    score: 71,
    banderas: [
      {
        regla: "unico_postor_alto",
        norma: "Art. 27 Reglamento Ley 32069",
        severidad: "alta",
        evidencia: "Único postor con oferta al 98.5% del valor referencial",
        fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/",
        opinionOece: "D008-2025",
      },
    ],
    fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/contracts/1370012-2026",
  },
  {
    id: "ALT-2026-0009",
    codigoconvocatoria: "1389560-2026",
    entidad: "Municipalidad Distrital de Wanchaq",
    rucEntidad: "20174892011",
    proveedor: "PROYECTOS DE INFRAESTRUCTURA SUR SAC",
    rucProveedor: "20602995118",
    edadRucDias: 89,
    unicoPostor: false,
    montoSoles: 3100000,
    fechaBuenaPro: "2026-02-15",
    objeto: "Construcción de mercado municipal Wanchaq",
    region: "Cusco",
    provincia: "Cusco",
    distrito: "Wanchaq",
    lat: -13.5311,
    lon: -71.9404,
    score: 67,
    banderas: [
      {
        regla: "edad_ruc_baja",
        norma: "Heurística — modelo Funes",
        severidad: "media",
        evidencia: "RUC creado hace 89 días",
        fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/",
        opinionOece: null,
      },
      {
        regla: "plazo_corto",
        norma: "Art. 64 Reglamento Ley 32069",
        severidad: "media",
        evidencia: "Plazo convocatoria→presentación: 6 días (mínimo legal: 8)",
        fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/",
        opinionOece: "D037-2025",
      },
    ],
    fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/contracts/1389560-2026",
  },
  {
    id: "ALT-2026-0010",
    codigoconvocatoria: "1410023-2026",
    entidad: "Municipalidad Distrital de Caraz",
    rucEntidad: "20162498770",
    proveedor: "EDIFICACIONES MODERNAS HUAYLAS EIRL",
    rucProveedor: "20614102983",
    edadRucDias: 18,
    unicoPostor: true,
    montoSoles: 1490000,
    fechaBuenaPro: "2026-04-22",
    objeto: "Construcción de cerco perimétrico complejo deportivo",
    region: "Áncash",
    provincia: "Huaylas",
    distrito: "Caraz",
    lat: -9.0464,
    lon: -77.8089,
    score: 93,
    banderas: [
      {
        regla: "edad_ruc_baja",
        norma: "Heurística — modelo Funes",
        severidad: "alta",
        evidencia: "RUC creado hace 18 días, ganó contrato por S/. 1.49M",
        fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/",
        opinionOece: null,
      },
      {
        regla: "unico_postor_alto",
        norma: "Art. 27 Reglamento Ley 32069",
        severidad: "alta",
        evidencia: "Único postor con oferta al 99.9% del valor referencial",
        fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/",
        opinionOece: "D008-2025",
      },
    ],
    fuenteUrl: "https://contratacionesabiertas.osce.gob.pe/contracts/1410023-2026",
  },
];

export const REPORTES_MOCK: ReporteCiudadano[] = [
  {
    id: "RPT-2026-0042",
    categoria: "obra_paralizada",
    descripcion:
      "Esta pista lleva 8 meses sin avanzar. Pusieron el cartel pero los trabajadores se fueron en agosto.",
    fotoUrl: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800",
    lat: -9.5128,
    lon: -77.5295,
    region: "Áncash",
    fecha: "2026-04-12",
    confirmado: true,
  },
  {
    id: "RPT-2026-0058",
    categoria: "obra_fantasma",
    descripcion:
      "El alcalde inauguró este colegio en Facebook hace dos meses pero por dentro está vacío, sin ventanas ni techo.",
    fotoUrl: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=800",
    lat: -9.1395,
    lon: -77.7472,
    region: "Áncash",
    fecha: "2026-04-28",
    confirmado: true,
  },
  {
    id: "RPT-2026-0061",
    categoria: "obra_paralizada",
    descripcion: "Maquinaria oxidándose, sin obreros desde febrero.",
    fotoUrl: "https://images.unsplash.com/photo-1517089152318-42ec560349c0?w=800",
    lat: -13.4138,
    lon: -71.8505,
    region: "Cusco",
    fecha: "2026-05-02",
    confirmado: false,
  },
  {
    id: "RPT-2026-0073",
    categoria: "funcionario_sospechoso",
    descripcion:
      "El subgerente maneja una camioneta nueva que no figura en su declaración jurada del año pasado.",
    lat: -9.0471,
    lon: -77.8094,
    region: "Áncash",
    fecha: "2026-05-09",
    confirmado: false,
  },
  {
    id: "RPT-2026-0080",
    categoria: "irregularidad_general",
    descripcion:
      "El mercado se inauguró pero no tiene servicios. Comerciantes pagaron por puestos que no existen.",
    fotoUrl: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800",
    lat: -13.5315,
    lon: -71.9398,
    region: "Cusco",
    fecha: "2026-05-13",
    confirmado: false,
  },
  {
    id: "RPT-2026-0085",
    categoria: "obra_paralizada",
    descripcion: "Un año exacto sin avance en la pista de la avenida principal.",
    lat: -9.276,
    lon: -77.6441,
    region: "Áncash",
    fecha: "2026-05-15",
    confirmado: false,
  },
];

export const CONVERGENCIAS_MOCK: Convergencia[] = [
  {
    id: "CNV-2026-001",
    alertaId: "ALT-2026-0001",
    reporteIds: ["RPT-2026-0042"],
    lat: -9.5123,
    lon: -77.5298,
    resumen:
      "Alerta de único postor con RUC de 47 días coincide con reporte ciudadano de obra paralizada hace 8 meses.",
  },
  {
    id: "CNV-2026-002",
    alertaId: "ALT-2026-0005",
    reporteIds: ["RPT-2026-0058"],
    lat: -9.1386,
    lon: -77.7465,
    resumen:
      "Alerta de tres banderas rojas (RUC nuevo + único postor + socio sancionado) sobre obra que el alcalde declaró inaugurada en Facebook.",
  },
  {
    id: "CNV-2026-003",
    alertaId: "ALT-2026-0009",
    reporteIds: ["RPT-2026-0080"],
    lat: -13.5313,
    lon: -71.9401,
    resumen:
      "Mercado Wanchaq: alerta de plazo legal incumplido + reporte ciudadano de obra inaugurada sin servicios.",
  },
];

export const METRICAS_MOCK: Metricas = {
  alertasActivas: ALERTAS_MOCK.length,
  reportesCiudadanos: REPORTES_MOCK.length,
  casosConvergentes: CONVERGENCIAS_MOCK.length,
  contratosVigilados: 14688,
  montoVigiladoSoles: 4250000000,
};

export const RESUMEN_REGIONES = [
  { region: "Áncash", alertas: 5, reportes: 4, monto: 10100000 },
  { region: "Cusco", alertas: 3, reportes: 2, monto: 9970000 },
  { region: "Lima", alertas: 1, reportes: 0, monto: 18900000 },
  { region: "Piura", alertas: 1, reportes: 0, monto: 6700000 },
];

export function formatSoles(n: number): string {
  if (n >= 1_000_000_000) return `S/. ${(n / 1_000_000_000).toFixed(2)} B`;
  if (n >= 1_000_000) return `S/. ${(n / 1_000_000).toFixed(2)} M`;
  if (n >= 1_000) return `S/. ${(n / 1_000).toFixed(0)} K`;
  return `S/. ${n}`;
}

export function severidadColor(s: "alta" | "media" | "baja"): string {
  if (s === "alta") return "text-crimson bg-crimson-soft border-crimson/20";
  if (s === "media") return "text-amber bg-amber-soft border-amber/20";
  return "text-ash bg-line border-ash/20";
}
