export type TipoEntidad =
  | "municipal_distrital"
  | "municipal_provincial"
  | "gobierno_regional"
  | "ministerio"
  | "empresa_publica"
  | "organismo_autonomo";

export interface Entidad {
  id: string;
  ruc: string;
  nombre: string;
  tipo: TipoEntidad;
  region: string;
  provincia?: string;
  distrito?: string;
  alertas: number;
  reportes: number;
  contratos: number;
  contratosVigilados: number;
  monto: number;
  scorePromedio: number;
  serie: number[]; // 6 meses
}

export const TIPO_LABELS: Record<TipoEntidad, string> = {
  municipal_distrital: "Municipalidad Distrital",
  municipal_provincial: "Municipalidad Provincial",
  gobierno_regional: "Gobierno Regional",
  ministerio: "Ministerio",
  empresa_publica: "Empresa Pública",
  organismo_autonomo: "Organismo Autónomo",
};

export const TIPO_SHORT: Record<TipoEntidad, string> = {
  municipal_distrital: "Mun. Distrital",
  municipal_provincial: "Mun. Provincial",
  gobierno_regional: "Gob. Regional",
  ministerio: "Ministerio",
  empresa_publica: "Empresa Pública",
  organismo_autonomo: "Org. Autónomo",
};

export const ENTIDADES: Entidad[] = [
  {
    id: "ent-001",
    ruc: "20131369981",
    nombre: "Municipalidad Distrital de Independencia",
    tipo: "municipal_distrital",
    region: "Áncash",
    provincia: "Huaraz",
    distrito: "Independencia",
    alertas: 2, reportes: 1, contratos: 84, contratosVigilados: 12,
    monto: 4_280_000, scorePromedio: 86,
    serie: [0, 1, 1, 1, 2, 2],
  },
  {
    id: "ent-002",
    ruc: "20165498220",
    nombre: "Municipalidad Distrital de Yungay",
    tipo: "municipal_distrital",
    region: "Áncash",
    provincia: "Yungay",
    distrito: "Yungay",
    alertas: 2, reportes: 2, contratos: 51, contratosVigilados: 8,
    monto: 4_250_000, scorePromedio: 91,
    serie: [0, 1, 1, 2, 2, 2],
  },
  {
    id: "ent-003",
    ruc: "20131380894",
    nombre: "Municipalidad Provincial de Lima",
    tipo: "municipal_provincial",
    region: "Lima",
    provincia: "Lima",
    alertas: 2, reportes: 0, contratos: 412, contratosVigilados: 38,
    monto: 18_900_000, scorePromedio: 65,
    serie: [0, 0, 1, 1, 2, 2],
  },
  {
    id: "ent-004",
    ruc: "20527268878",
    nombre: "Gobierno Regional de Cusco",
    tipo: "gobierno_regional",
    region: "Cusco",
    alertas: 2, reportes: 1, contratos: 287, contratosVigilados: 24,
    monto: 7_140_000, scorePromedio: 64,
    serie: [0, 1, 1, 1, 2, 2],
  },
  {
    id: "ent-005",
    ruc: "20484020611",
    nombre: "Gobierno Regional de Piura",
    tipo: "gobierno_regional",
    region: "Piura",
    alertas: 1, reportes: 0, contratos: 198, contratosVigilados: 15,
    monto: 6_700_000, scorePromedio: 88,
    serie: [0, 0, 0, 1, 1, 1],
  },
  {
    id: "ent-006",
    ruc: "20530906978",
    nombre: "Gobierno Regional de La Libertad",
    tipo: "gobierno_regional",
    region: "La Libertad",
    alertas: 2, reportes: 0, contratos: 234, contratosVigilados: 18,
    monto: 6_700_000, scorePromedio: 82,
    serie: [0, 0, 1, 1, 2, 2],
  },
  {
    id: "ent-007",
    ruc: "20171298320",
    nombre: "Municipalidad Provincial de Carhuaz",
    tipo: "municipal_provincial",
    region: "Áncash",
    provincia: "Carhuaz",
    alertas: 1, reportes: 0, contratos: 42, contratosVigilados: 6,
    monto: 980_000, scorePromedio: 78,
    serie: [0, 0, 0, 1, 1, 1],
  },
  {
    id: "ent-008",
    ruc: "20171587029",
    nombre: "Municipalidad Distrital de Recuay",
    tipo: "municipal_distrital",
    region: "Áncash",
    provincia: "Recuay",
    distrito: "Recuay",
    alertas: 1, reportes: 0, contratos: 38, contratosVigilados: 5,
    monto: 540_000, scorePromedio: 71,
    serie: [0, 0, 1, 1, 1, 1],
  },
  {
    id: "ent-009",
    ruc: "20162498770",
    nombre: "Municipalidad Distrital de Caraz",
    tipo: "municipal_distrital",
    region: "Áncash",
    provincia: "Huaylas",
    distrito: "Caraz",
    alertas: 1, reportes: 1, contratos: 46, contratosVigilados: 7,
    monto: 1_490_000, scorePromedio: 93,
    serie: [0, 0, 0, 1, 1, 1],
  },
  {
    id: "ent-010",
    ruc: "20174521329",
    nombre: "Municipalidad Distrital de San Sebastián",
    tipo: "municipal_distrital",
    region: "Cusco",
    provincia: "Cusco",
    distrito: "San Sebastián",
    alertas: 1, reportes: 0, contratos: 52, contratosVigilados: 6,
    monto: 1_750_000, scorePromedio: 52,
    serie: [0, 0, 1, 1, 1, 1],
  },
  {
    id: "ent-011",
    ruc: "20174892011",
    nombre: "Municipalidad Distrital de Wanchaq",
    tipo: "municipal_distrital",
    region: "Cusco",
    provincia: "Cusco",
    distrito: "Wanchaq",
    alertas: 1, reportes: 1, contratos: 49, contratosVigilados: 7,
    monto: 3_100_000, scorePromedio: 67,
    serie: [0, 0, 0, 1, 1, 1],
  },
  {
    id: "ent-012",
    ruc: "20131370645",
    nombre: "Ministerio de Salud",
    tipo: "ministerio",
    region: "Lima",
    alertas: 3, reportes: 1, contratos: 1248, contratosVigilados: 96,
    monto: 12_400_000, scorePromedio: 72,
    serie: [1, 2, 2, 2, 3, 3],
  },
  {
    id: "ent-013",
    ruc: "20131372718",
    nombre: "Ministerio de Transportes y Comunicaciones",
    tipo: "ministerio",
    region: "Lima",
    alertas: 4, reportes: 0, contratos: 2104, contratosVigilados: 175,
    monto: 38_200_000, scorePromedio: 78,
    serie: [1, 2, 3, 3, 4, 4],
  },
  {
    id: "ent-014",
    ruc: "20131370998",
    nombre: "Ministerio de Educación",
    tipo: "ministerio",
    region: "Lima",
    alertas: 2, reportes: 1, contratos: 894, contratosVigilados: 62,
    monto: 9_800_000, scorePromedio: 66,
    serie: [0, 1, 1, 1, 2, 2],
  },
  {
    id: "ent-015",
    ruc: "20100027461",
    nombre: "PETROPERÚ S.A.",
    tipo: "empresa_publica",
    region: "Lima",
    alertas: 2, reportes: 0, contratos: 612, contratosVigilados: 48,
    monto: 22_400_000, scorePromedio: 81,
    serie: [0, 1, 1, 2, 2, 2],
  },
  {
    id: "ent-016",
    ruc: "20100139560",
    nombre: "SEDAPAL S.A.",
    tipo: "empresa_publica",
    region: "Lima",
    alertas: 1, reportes: 1, contratos: 384, contratosVigilados: 28,
    monto: 11_700_000, scorePromedio: 74,
    serie: [0, 0, 1, 1, 1, 1],
  },
  {
    id: "ent-017",
    ruc: "20158395621",
    nombre: "Municipalidad Provincial de Trujillo",
    tipo: "municipal_provincial",
    region: "La Libertad",
    provincia: "Trujillo",
    alertas: 2, reportes: 1, contratos: 156, contratosVigilados: 16,
    monto: 6_700_000, scorePromedio: 82,
    serie: [0, 0, 1, 1, 1, 2],
  },
  {
    id: "ent-018",
    ruc: "20217083083",
    nombre: "Gobierno Regional de Áncash",
    tipo: "gobierno_regional",
    region: "Áncash",
    alertas: 1, reportes: 0, contratos: 312, contratosVigilados: 25,
    monto: 5_400_000, scorePromedio: 79,
    serie: [0, 0, 0, 0, 1, 1],
  },
  {
    id: "ent-019",
    ruc: "20193393175",
    nombre: "Municipalidad Provincial de Huancayo",
    tipo: "municipal_provincial",
    region: "Junín",
    provincia: "Huancayo",
    alertas: 2, reportes: 1, contratos: 134, contratosVigilados: 13,
    monto: 5_800_000, scorePromedio: 71,
    serie: [0, 0, 1, 1, 1, 2],
  },
  {
    id: "ent-020",
    ruc: "20100143288",
    nombre: "ENAPU S.A.",
    tipo: "empresa_publica",
    region: "Lima",
    alertas: 1, reportes: 0, contratos: 198, contratosVigilados: 12,
    monto: 4_900_000, scorePromedio: 68,
    serie: [0, 0, 0, 1, 1, 1],
  },
  {
    id: "ent-021",
    ruc: "20131378972",
    nombre: "Contraloría General de la República",
    tipo: "organismo_autonomo",
    region: "Lima",
    alertas: 0, reportes: 0, contratos: 184, contratosVigilados: 4,
    monto: 0, scorePromedio: 0,
    serie: [0, 0, 0, 0, 0, 0],
  },
  {
    id: "ent-022",
    ruc: "20165498003",
    nombre: "Municipalidad Distrital de Pataz",
    tipo: "municipal_distrital",
    region: "La Libertad",
    provincia: "Pataz",
    distrito: "Pataz",
    alertas: 1, reportes: 0, contratos: 28, contratosVigilados: 4,
    monto: 2_900_000, scorePromedio: 90,
    serie: [0, 0, 0, 1, 1, 1],
  },
  {
    id: "ent-023",
    ruc: "20531507385",
    nombre: "Gobierno Regional de Arequipa",
    tipo: "gobierno_regional",
    region: "Arequipa",
    alertas: 1, reportes: 1, contratos: 247, contratosVigilados: 18,
    monto: 4_200_000, scorePromedio: 73,
    serie: [0, 0, 0, 1, 1, 1],
  },
  {
    id: "ent-024",
    ruc: "20447382937",
    nombre: "Municipalidad Provincial de Maynas",
    tipo: "municipal_provincial",
    region: "Loreto",
    provincia: "Maynas",
    alertas: 1, reportes: 0, contratos: 89, contratosVigilados: 9,
    monto: 2_500_000, scorePromedio: 58,
    serie: [0, 0, 0, 0, 1, 1],
  },
  {
    id: "ent-025",
    ruc: "20210826820",
    nombre: "Municipalidad Provincial de Espinar",
    tipo: "municipal_provincial",
    region: "Cusco",
    provincia: "Espinar",
    alertas: 1, reportes: 0, contratos: 62, contratosVigilados: 8,
    monto: 2_580_000, scorePromedio: 81,
    serie: [0, 0, 0, 1, 1, 1],
  },
];

export function entidadById(ruc: string): Entidad | undefined {
  return ENTIDADES.find((e) => e.ruc === ruc);
}
